# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shoppinglist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to=shoppinglist.models.upload_location, width_field='image_width')),
                ('image_height', models.IntegerField(default=300)),
                ('image_width', models.IntegerField(default=300)),
                ('private', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('finalized', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finalized_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pending', '-due_date', '-updated', 'created'],
            },
        ),
    ]
